### ISSUE TITLE
Account activation and at least also reset links are broken

### ISSUE THREAD

**Issue by idl0r** [SecurityRAT/SecurityRAT#209]
Hi,

we're running 1.8.7. Register works, the user gets the mail including the link:
https://securityrat.example.com/account/activate?key=somekey
This results into a 404 page from securityrat. Removing "/account" from the URL seems to work.
The same for password reset except that it still doesn't do anything when removing /account from the URL.

It also seems to log some template issues:
```
securityrat-6cbcd7d84-6j7gf securityrat 2023-09-27 08:35:02.120 ERROR 11 --- [rity-rat-task-2] org.thymeleaf.TemplateEngine             : [THYMELEAF][security-rat-task-2] Exception processing template "mail/activationPasswordEmail": Error resolving template [mail/activationPasswordEmail], template might not exist or might not be accessible by any of the configured Template Resolvers
securityrat-6cbcd7d84-6j7gf securityrat 
securityrat-6cbcd7d84-6j7gf securityrat org.thymeleaf.exceptions.TemplateInputException: Error resolving template [mail/activationPasswordEmail], template might not exist or might not be accessible by any of the configured Template Resolvers
securityrat-6cbcd7d84-6j7gf securityrat     at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869)
securityrat-6cbcd7d84-6j7gf securityrat     at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607)
securityrat-6cbcd7d84-6j7gf securityrat     at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
securityrat-6cbcd7d84-6j7gf securityrat     at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1059)
securityrat-6cbcd7d84-6j7gf securityrat     at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1048)
securityrat-6cbcd7d84-6j7gf securityrat     at org.appsec.securityrat.provider.MailService.sendActivationPassword(MailService.java:52)
securityrat-6cbcd7d84-6j7gf securityrat     at org.appsec.securityrat.provider.MailService$$FastClassBySpringCGLIB$$ffde805e.invoke(<generated>)
securityrat-6cbcd7d84-6j7gf securityrat     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
securityrat-6cbcd7d84-6j7gf securityrat     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
securityrat-6cbcd7d84-6j7gf securityrat     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
securityrat-6cbcd7d84-6j7gf securityrat     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
securityrat-6cbcd7d84-6j7gf securityrat     at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
securityrat-6cbcd7d84-6j7gf securityrat     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
securityrat-6cbcd7d84-6j7gf securityrat     at io.github.jhipster.async.ExceptionHandlingAsyncTaskExecutor.lambda$createWrappedRunnable$1(ExceptionHandlingAsyncTaskExecutor.java:78)
securityrat-6cbcd7d84-6j7gf securityrat     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
securityrat-6cbcd7d84-6j7gf securityrat     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
securityrat-6cbcd7d84-6j7gf securityrat     at java.base/java.lang.Thread.run(Unknown Source) 
```

Which I don't get because it's already built in into the JAR file? The mail also looks fine to me and seems to be whats written into the template.

Any ideas?
The "Logs" item under Administration->Logs seems just a text but no actual link. It's not working either. Anything else there seems to work.

**Comment by daylicron** [comment]
I'm facing the same issue. Does anybody have a clue?

**Comment by AresSec** [comment]
Hi @idl0r and @daylicron,
sorry for the really late reply. So just for the understanding: registration works, email gets send out, but the URL in the activation link within the email is not correct?

Tips for a quick workaround: the admin account can activate every user within the frontend under Administration -> User Management and then click on the button "Activated" Yes or No.
